"""Translate Swedish common.rpy — replace English stubs with Swedish translations."""
import re, pathlib

SRC = pathlib.Path(r"c:\Users\eriks\Documents\dev\hammerofsteel\theCK\Amelia_V2\game\tl\swedish\common.rpy")

# Dictionary: English → Swedish for common Ren'Py strings
T = {
    # 000statements
    "Click to play the video.": "Klicka för att spela videon.",
    # accessibility
    "Self-voicing disabled.": "Självuppläsning avaktiverad.",
    "Clipboard voicing enabled. ": "Klippbordsuppläsning aktiverad. ",
    "Self-voicing enabled. ": "Självuppläsning aktiverad. ",
    "bar": "reglage",
    "selected": "markerad",
    "viewport": "visningsruta",
    "horizontal scroll": "horisontell rullning",
    "vertical scroll": "vertikal rullning",
    "activate": "aktivera",
    "deactivate": "avaktivera",
    "increase": "öka",
    "decrease": "minska",
    "Self-Voicing": "Självuppläsning",
    "Self-voicing support is limited when using a touch screen.": "Stöd för självuppläsning är begränsat vid pekskärm.",
    "Off": "Av",
    "Text-to-speech": "Text-till-tal",
    "Clipboard": "Klippbord",
    "Debug": "Felsökning",
    "Voice Volume": "Röstvolym",
    "Reset": "Återställ",
    "Self-Voicing Volume Drop": "Volymsänkning vid självuppläsning",
    "Mono Audio": "Monoljud",
    "Enable": "Aktivera",
    "Font Override": "Teckensnittsåsidosättning",
    "Default": "Standard",
    "DejaVu Sans": "DejaVu Sans",
    "Opendyslexic": "Opendyslexic",
    "High Contrast Text": "Text med hög kontrast",
    "Text Size Scaling": "Textstorleksskalning",
    "Line Spacing Scaling": "Radavståndsskalning",
    "Kerning": "Kerning",
    "Accessibility Menu. Use up and down arrows to navigate, and enter to activate buttons and bars.": "Tillgänglighetsmeny. Använd upp- och nedpilar för att navigera och Enter för att aktivera knappar och reglage.",
    "Self-Voicing and Audio": "Självuppläsning och ljud",
    "Text": "Text",
    "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was.": "Alternativen i denna meny syftar till att förbättra tillgängligheten. De kanske inte fungerar med alla spel, och vissa kombinationer kan göra spelet ospelbart. Det är inte ett fel i spelet eller motorn. För bäst resultat vid byte av teckensnitt, försök behålla textstorleken som den ursprungligen var.",
    # Weekdays
    "{#weekday}Monday": "{#weekday}Måndag",
    "{#weekday}Tuesday": "{#weekday}Tisdag",
    "{#weekday}Wednesday": "{#weekday}Onsdag",
    "{#weekday}Thursday": "{#weekday}Torsdag",
    "{#weekday}Friday": "{#weekday}Fredag",
    "{#weekday}Saturday": "{#weekday}Lördag",
    "{#weekday}Sunday": "{#weekday}Söndag",
    "{#weekday_short}Mon": "{#weekday_short}Mån",
    "{#weekday_short}Tue": "{#weekday_short}Tis",
    "{#weekday_short}Wed": "{#weekday_short}Ons",
    "{#weekday_short}Thu": "{#weekday_short}Tor",
    "{#weekday_short}Fri": "{#weekday_short}Fre",
    "{#weekday_short}Sat": "{#weekday_short}Lör",
    "{#weekday_short}Sun": "{#weekday_short}Sön",
    # Months
    "{#month}January": "{#month}Januari",
    "{#month}February": "{#month}Februari",
    "{#month}March": "{#month}Mars",
    "{#month}April": "{#month}April",
    "{#month}May": "{#month}Maj",
    "{#month}June": "{#month}Juni",
    "{#month}July": "{#month}Juli",
    "{#month}August": "{#month}Augusti",
    "{#month}September": "{#month}September",
    "{#month}October": "{#month}Oktober",
    "{#month}November": "{#month}November",
    "{#month}December": "{#month}December",
    "{#month_short}Jan": "{#month_short}Jan",
    "{#month_short}Feb": "{#month_short}Feb",
    "{#month_short}Mar": "{#month_short}Mar",
    "{#month_short}Apr": "{#month_short}Apr",
    "{#month_short}May": "{#month_short}Maj",
    "{#month_short}Jun": "{#month_short}Jun",
    "{#month_short}Jul": "{#month_short}Jul",
    "{#month_short}Aug": "{#month_short}Aug",
    "{#month_short}Sep": "{#month_short}Sep",
    "{#month_short}Oct": "{#month_short}Okt",
    "{#month_short}Nov": "{#month_short}Nov",
    "{#month_short}Dec": "{#month_short}Dec",
    # Date format
    "%b %d, %H:%M": "%d %b, %H:%M",
    # Save/load
    "Save slot %s: [text]": "Spara plats %s: [text]",
    "Load slot %s: [text]": "Ladda plats %s: [text]",
    "Delete slot [text]": "Radera plats [text]",
    "File page auto": "Filsida auto",
    "File page quick": "Filsida snabb",
    "File page [text]": "Filsida [text]",
    "Next file page.": "Nästa filsida.",
    "Previous file page.": "Föregående filsida.",
    "Quick save complete.": "Snabbsparning klar.",
    "Quick save.": "Snabbspara.",
    "Quick load.": "Snabbladda.",
    # Actions
    "Language [text]": "Språk [text]",
    "Open [text] directory.": "Öppna [text]-mappen.",
    # Director
    "The interactive director is not enabled here.": "Den interaktiva regissören är inte aktiverad här.",
    "Done": "Klar",
    "(statement)": "(sats)",
    "(tag)": "(tagg)",
    "(attributes)": "(attribut)",
    "(transform)": "(transform)",
    "(transition)": "(övergång)",
    "(channel)": "(kanal)",
    "(filename)": "(filnamn)",
    "Change": "Ändra",
    "Add": "Lägg till",
    "Cancel": "Avbryt",
    "Remove": "Ta bort",
    "Statement:": "Sats:",
    "Tag:": "Tagg:",
    "Attributes:": "Attribut:",
    "Click to toggle attribute, right click to toggle negative attribute.": "Klicka för att växla attribut, högerklicka för att växla negativt attribut.",
    "Transforms:": "Transformationer:",
    "Click to set transform, right click to add to transform list.": "Klicka för att ange transformation, högerklicka för att lägga till i transformationslistan.",
    "Customize director.transforms to add more transforms.": "Anpassa director.transforms för att lägga till fler transformationer.",
    "Behind:": "Bakom:",
    "Click to set, right click to add to behind list.": "Klicka för att ange, högerklicka för att lägga till i bakomlistan.",
    "Transition:": "Övergång:",
    "Click to set.": "Klicka för att ange.",
    "Customize director.transitions to add more transitions.": "Anpassa director.transitions för att lägga till fler övergångar.",
    "Channel:": "Kanal:",
    "Customize director.audio_channels to add more channels.": "Anpassa director.audio_channels för att lägga till fler kanaler.",
    "Audio Filename:": "Ljudfilnamn:",
    # GUI confirmation
    "Are you sure?": "Är du säker?",
    "Are you sure you want to delete this save?": "Är du säker på att du vill radera denna sparfil?",
    "Are you sure you want to overwrite your save?": "Är du säker på att du vill skriva över din sparfil?",
    "Loading will lose unsaved progress.\nAre you sure you want to do this?": "Att ladda förlorar osparade framsteg.\nÄr du säker på att du vill göra detta?",
    "Are you sure you want to quit?": "Är du säker på att du vill avsluta?",
    "Are you sure you want to return to the main menu?\nThis will lose unsaved progress.": "Är du säker på att du vill återvända till huvudmenyn?\nOsparade framsteg går förlorade.",
    "Are you sure you want to continue where you left off?": "Är du säker på att du vill fortsätta där du slutade?",
    "Are you sure you want to end the replay?": "Är du säker på att du vill avsluta reprisen?",
    "Are you sure you want to begin skipping?": "Är du säker på att du vill börja hoppa över?",
    "Are you sure you want to skip to the next choice?": "Är du säker på att du vill hoppa till nästa val?",
    "Are you sure you want to skip unseen dialogue to the next choice?": "Är du säker på att du vill hoppa över oläst dialog till nästa val?",
    "This save was created on a different device. Maliciously constructed save files can harm your computer. Do you trust this save's creator and everyone who could have changed the file?": "Denna sparfil skapades på en annan enhet. Illvilligt konstruerade sparfiler kan skada din dator. Litar du på sparfilens skapare och alla som kan ha ändrat filen?",
    "Do you trust the device the save was created on? You should only choose yes if you are the device's sole user.": "Litar du på enheten som sparfilen skapades på? Du bör bara välja ja om du är enhetens enda användare.",
    # Keymap
    "Failed to save screenshot as %s.": "Kunde inte spara skärmbild som %s.",
    "Saved screenshot as %s.": "Sparade skärmbild som %s.",
    # Library
    "Skip Mode": "Överhoppningsläge",
    "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}.": "Detta program innehåller fri programvara under flera licenser, inklusive MIT-licensen och GNU Lesser General Public License. En komplett lista över programvara, inklusive länkar till fullständig källkod, finns {a=https://www.renpy.org/l/license}här{/a}.",
    # Preferences internal
    "display": "visning",
    "transitions": "övergångar",
    "skip transitions": "hoppa över övergångar",
    "video sprites": "videosprites",
    "show empty window": "visa tomt fönster",
    "text speed": "texthastighet",
    "joystick": "joystick",
    "joystick...": "joystick...",
    "skip": "hoppa över",
    "skip unseen [text]": "hoppa över oläst [text]",
    "skip unseen text": "hoppa över oläst text",
    "begin skipping": "börja hoppa över",
    "after choices": "efter val",
    "skip after choices": "hoppa över efter val",
    "auto-forward time": "automatisk frammatningstid",
    "auto-forward": "automatisk frammatning",
    "Auto forward": "Automatisk frammatning",
    "auto-forward after click": "automatisk frammatning efter klick",
    "automatic move": "automatisk flytt",
    "wait for voice": "vänta på röst",
    "voice sustain": "håll kvar röst",
    "self voicing": "självuppläsning",
    "self voicing enable": "aktivera självuppläsning",
    "self voicing disable": "avaktivera självuppläsning",
    "self voicing volume drop": "volymsänkning vid självuppläsning",
    "clipboard voicing": "klippbordsuppläsning",
    "clipboard voicing enable": "aktivera klippbordsuppläsning",
    "clipboard voicing disable": "avaktivera klippbordsuppläsning",
    "debug voicing": "felsökningsuppläsning",
    "debug voicing enable": "aktivera felsökningsuppläsning",
    "debug voicing disable": "avaktivera felsökningsuppläsning",
    "emphasize audio": "betona ljud",
    "rollback side": "tillbakarullningssida",
    "gl powersave": "gl energispar",
    "gl framerate": "gl bildfrekvens",
    "gl tearing": "gl tearing",
    "font transform": "teckensnittstransformation",
    "font size": "teckenstorlek",
    "font line spacing": "radavstånd för teckensnitt",
    "system cursor": "systemmarkör",
    "renderer menu": "renderarmeny",
    "accessibility menu": "tillgänglighetsmeny",
    "high contrast text": "text med hög kontrast",
    "audio when minimized": "ljud vid minimering",
    "audio when unfocused": "ljud utan fokus",
    "web cache preload": "förladdning av webbcache",
    "voice after game menu": "röst efter spelmeny",
    "restore window position": "återställ fönsterposition",
    "mono audio": "monoljud",
    "font kerning": "kerning för teckensnitt",
    "reset": "återställ",
    "main volume": "huvudvolym",
    "music volume": "musikvolym",
    "sound volume": "ljudvolym",
    "voice volume": "röstvolym",
    "mute main": "stäng av huvudljud",
    "mute music": "stäng av musik",
    "mute sound": "stäng av ljud",
    "mute voice": "stäng av röst",
    "mute all": "stäng av allt",
    "Clipboard voicing enabled. Press 'shift+C' to disable.": "Klippbordsuppläsning aktiverad. Tryck 'shift+C' för att avaktivera.",
    'Self-voicing would say \\"[renpy.display.tts.last]\\". Press \'alt+shift+V\' to disable.': 'Självuppläsning skulle säga \\"[renpy.display.tts.last]\\". Tryck \'alt+shift+V\' för att avaktivera.',
    "Self-voicing enabled. Press 'v' to disable.": "Självuppläsning aktiverad. Tryck 'v' för att avaktivera.",
    # Speech bubble
    "Speech Bubble Editor": "Pratbubbleredigerare",
    "(hide)": "(dölj)",
    "(clear retained bubbles)": "(rensa sparade bubblor)",
    # Sync
    "Sync downloaded.": "Synk nedladdad.",
    "Could not connect to the Ren'Py Sync server.": "Kunde inte ansluta till Ren'Py Sync-servern.",
    "The Ren'Py Sync server timed out.": "Ren'Py Sync-servern svarade inte i tid.",
    "An unknown error occurred while connecting to the Ren'Py Sync server.": "Ett okänt fel uppstod vid anslutning till Ren'Py Sync-servern.",
    "The Ren'Py Sync server does not have a copy of this sync. The sync ID may be invalid, or it may have timed out.": "Ren'Py Sync-servern har inte en kopia av denna synk. Synk-ID:t kan vara ogiltigt eller ha löpt ut.",
    "Please enter the sync ID you generated.\nNever enter a sync ID you didn't create yourself.": "Ange det synk-ID du genererade.\nAnge aldrig ett synk-ID du inte skapade själv.",
    "The sync ID is not in the correct format.": "Synk-ID:t har inte rätt format.",
    "The sync could not be decrypted.": "Synkroniseringen kunde inte dekrypteras.",
    "The sync belongs to a different game.": "Synkroniseringen tillhör ett annat spel.",
    "The sync contains a file with an invalid name.": "Synkroniseringen innehåller en fil med ogiltigt namn.",
    "This will upload your saves to the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}.\nDo you want to continue?": "Detta laddar upp dina sparfiler till {a=https://sync.renpy.org}Ren'Py Sync-servern{/a}.\nVill du fortsätta?",
    "Enter Sync ID": "Ange synk-ID",
    "This will contact the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}.": "Detta kontaktar {a=https://sync.renpy.org}Ren'Py Sync-servern{/a}.",
    "Sync Success": "Synkronisering lyckades",
    "The Sync ID is:": "Synk-ID:t är:",
    "You can use this ID to download your save on another device.\nThis sync will expire in an hour.\nRen'Py Sync is supported by {a=https://www.renpy.org/sponsors.html}Ren'Py's Sponsors{/a}.": "Du kan använda detta ID för att ladda ner din sparfil på en annan enhet.\nDenna synk löper ut om en timme.\nRen'Py Sync stöds av {a=https://www.renpy.org/sponsors.html}Ren'Pys sponsorer{/a}.",
    "Continue": "Fortsätt",
    "Sync Error": "Synkfel",
    # Translation
    "Translation identifier: [identifier]": "Översättnings-ID: [identifier]",
    " translates [tl.filename]:[tl.linenumber]": " översätter [tl.filename]:[tl.linenumber]",
    "\n{color=#fff}Copied to clipboard.{/color}": "\n{color=#fff}Kopierat till klippbordet.{/color}",
    # IAP
    "Contacting App Store\nPlease Wait...": "Kontaktar App Store\nVänta...",
    # Updater
    "No update methods found.": "Inga uppdateringsmetoder hittades.",
    "Could not download file list: ": "Kunde inte ladda ner fillistan: ",
    "File list digest does not match.": "Fillistans kontrollsumma stämmer inte.",
    "An error is being simulated.": "Ett fel simuleras.",
    "Either this project does not support updating, or the update status file was deleted.": "Antingen stöder detta projekt inte uppdatering, eller så har uppdateringsstatusfilen raderats.",
    "This account does not have permission to perform an update.": "Detta konto har inte behörighet att utföra en uppdatering.",
    "This account does not have permission to write the update log.": "Detta konto har inte behörighet att skriva uppdateringsloggen.",
    "Could not verify update signature.": "Kunde inte verifiera uppdateringssignaturen.",
    "The update file was not downloaded.": "Uppdateringsfilen laddades inte ner.",
    "The update file does not have the correct digest - it may have been corrupted.": "Uppdateringsfilen har inte rätt kontrollsumma - den kan vara skadad.",
    "While unpacking {}, unknown type {}.": "Vid uppackning av {}, okänd typ {}.",
    "Updater": "Uppdaterare",
    "An error has occurred:": "Ett fel har uppstått:",
    "Checking for updates.": "Söker efter uppdateringar.",
    "This program is up to date.": "Detta program är uppdaterat.",
    "[u.version] is available. Do you want to install it?": "[u.version] är tillgänglig. Vill du installera den?",
    "Preparing to download the updates.": "Förbereder nedladdning av uppdateringar.",
    "Downloading the updates.": "Laddar ner uppdateringar.",
    "Unpacking the updates.": "Packar upp uppdateringar.",
    "Finishing up.": "Avslutar.",
    "The updates have been installed. The program will restart.": "Uppdateringarna har installerats. Programmet startas om.",
    "The updates have been installed.": "Uppdateringarna har installerats.",
    "The updates were cancelled.": "Uppdateringarna avbröts.",
    "Proceed": "Fortsätt",
    "Preparing to download the game data.": "Förbereder nedladdning av spelets data.",
    "Downloading the game data.": "Laddar ner spelets data.",
    "The game data has been downloaded.": "Spelets data har laddats ner.",
    "An error occurred when trying to download game data:": "Ett fel uppstod vid nedladdning av spelets data:",
    "This game cannot be run until the game data has been downloaded.": "Detta spel kan inte köras förrän spelets data har laddats ner.",
    "Retry": "Försök igen",
    # Gallery
    "Image [index] of [count] locked.": "Bild [index] av [count] låst.",
    "prev": "föreg.",
    "next": "nästa",
    "slideshow": "bildspel",
    "return": "tillbaka",
    # GL test
    "Renderer": "Renderare",
    "Automatically Choose": "Välj automatiskt",
    "Force GL2 Renderer": "Tvinga GL2-renderare",
    "Force ANGLE2 Renderer": "Tvinga ANGLE2-renderare",
    "Force GLES2 Renderer": "Tvinga GLES2-renderare",
    "Enable (No Blocklist)": "Aktivera (ingen blocklista)",
    "Powersave": "Energispar",
    "Framerate": "Bildfrekvens",
    "Screen": "Skärm",
    "60": "60",
    "30": "30",
    "Tearing": "Tearing",
    "Changes will take effect the next time this program is run.": "Ändringarna träder i kraft nästa gång programmet körs.",
    "Performance Warning": "Prestandavarning",
    "This computer is using software rendering.": "Den här datorn använder mjukvarurenderering.",
    "This game requires use of GL2 that can't be initialised.": "Detta spel kräver GL2 som inte kan initieras.",
    "This computer has a problem displaying graphics: [problem].": "Den här datorn har problem med att visa grafik: [problem].",
    "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display.": "Grafikdrivrutinerna kan vara föråldrade eller fungerar inte korrekt. Det kan leda till långsam eller felaktig grafik.",
    "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer.": "Filen {a=edit:1:log.txt}log.txt{/a} kan innehålla information som hjälper dig att avgöra vad som är fel med din dator.",
    "More details on how to fix this can be found in the {a=[url]}documentation{/a}.": "Mer information om hur du åtgärdar detta finns i {a=[url]}dokumentationen{/a}.",
    "Continue, Show this warning again": "Fortsätt, visa denna varning igen",
    "Continue, Don't show warning again": "Fortsätt, visa inte denna varning igen",
    "Change render options": "Ändra renderingsalternativ",
    # Gamepad
    "Select Gamepad to Calibrate": "Välj spelkontroll att kalibrera",
    "No Gamepads Available": "Inga spelkontroller tillgängliga",
    "Calibrating [name] ([i]/[total])": "Kalibrerar [name] ([i]/[total])",
    "Press or move the '[control!s]' [kind].": "Tryck eller rör på '[control!s]' [kind].",
    "Skip (A)": "Hoppa över (A)",
    "Back (B)": "Tillbaka (B)",
    # Error handling
    "Open": "Öppna",
    "Opens the traceback.txt file in a text editor.": "Öppnar filen traceback.txt i en textredigerare.",
    "Copy BBCode": "Kopiera BBCode",
    "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/.": "Kopierar filen traceback.txt till klippbordet som BBcode för forum som https://lemmasoft.renai.us/.",
    "Copy Markdown": "Kopiera Markdown",
    "Copies the traceback.txt file to the clipboard as Markdown for Discord.": "Kopierar filen traceback.txt till klippbordet som Markdown för Discord.",
    "An exception has occurred.": "Ett undantag har inträffat.",
    "Rollback": "Återrullning",
    "Attempts a roll back to a prior time, allowing you to save or choose a different choice.": "Försöker rulla tillbaka till en tidigare tidpunkt, så att du kan spara eller göra ett annat val.",
    "Ignore": "Ignorera",
    "Ignores the exception, allowing you to continue.": "Ignorerar undantaget och låter dig fortsätta.",
    "Ignores the exception, allowing you to continue. This often leads to additional errors.": "Ignorerar undantaget och låter dig fortsätta. Det leder ofta till ytterligare fel.",
    "Reload": "Ladda om",
    "Reloads the game from disk, saving and restoring game state if possible.": "Laddar om spelet från disk, sparar och återställer spelstatus om möjligt.",
    "Console": "Konsol",
    "Opens a console to allow debugging the problem.": "Öppnar en konsol för felsökning av problemet.",
    "Quits the game.": "Avslutar spelet.",
    "Parsing the script failed.": "Tolkning av skriptet misslyckades.",
}

text = SRC.read_text(encoding="utf-8")
lines = text.split("\n")
out = []
i = 0
translated = 0
while i < len(lines):
    line = lines[i]
    # Look for `    old "..."` followed by `    new "..."`
    m_old = re.match(r'^(\s+)old "(.*)"$', line)
    if m_old and i + 1 < len(lines):
        m_new = re.match(r'^(\s+)new "(.*)"$', lines[i + 1])
        if m_new:
            eng = m_old.group(2)
            if eng in T:
                out.append(line)
                out.append(f'{m_new.group(1)}new "{T[eng]}"')
                translated += 1
                i += 2
                continue
    out.append(line)
    i += 1

SRC.write_text("\n".join(out), encoding="utf-8")
print(f"Translated {translated} strings in common.rpy")
